version: '3'

services:
  elasticsearch:
    build: ./.docker/elasticsearch
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - .docker/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  es_data:
    driver: local
  db_data:
    driver: local
